"""Add courses table and role column to users

Revision ID: 3058f242e71a
Revises: a915789fe517
Create Date: 2025-04-26 00:12:30.535959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3058f242e71a'
down_revision: Union[str, None] = 'a915789fe517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
#     # ### end Alembic commands ###

def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy.sql import table, column

    # Define a lightweight "users" table for data update
    users = table('users',
        column('role', sa.String),
    )

    # Step 1: Add "role" column as nullable
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))

    # Step 2: Update all existing rows to have role='USER'
    op.execute(users.update().values(role='USER'))

    # Step 3: Alter column to make it NOT NULL
    op.alter_column('users', 'role', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
