"""add_resume_embedding_to_users

Revision ID: a05cf28e6733
Revises: 36564fdf934d
Create Date: 2025-06-28 23:25:30.978648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05cf28e6733'
down_revision: Union[str, None] = '36564fdf934d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume_embedding')
    # ### end Alembic commands ###
