"""Create courses table

Revision ID: c44d0ee41f5b
Revises: 3058f242e71a
Create Date: 2025-04-26 10:51:45.724196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44d0ee41f5b'
down_revision: Union[str, None] = '3058f242e71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.String(length=100), nullable=False),
    sa.Column('course_name', sa.Text(), nullable=False),
    sa.Column('course_description', sa.Text(), nullable=False),
    sa.Column('prerequisites', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=False),
    sa.Column('domains', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('skills_associated', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('combined_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
