"""add_profile_enhancement_fields_and_foundational_courses

Revision ID: 82e7fbcae12e
Revises: b426e3ba287b
Create Date: 2025-07-03 22:27:33.280958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e7fbcae12e'
down_revision: Union[str, None] = 'b426e3ba287b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
