"""create_recommendations_table

Revision ID: f624550097f5
Revises: 19bdb8bc6d9e
Create Date: 2025-07-10 18:28:33.262976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f624550097f5'
down_revision: Union[str, None] = '19bdb8bc6d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('top_k_requested', sa.Integer(), nullable=False),
    sa.Column('eligible_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ineligible_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_matches', sa.Integer(), nullable=True),
    sa.Column('processing_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('system_health', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prerequisite_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_completed_courses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resume_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keyword_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    # ### end Alembic commands ###
